version: '3'

services:
 mongo:
    image: mongo:3
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: pato
      MONGO_INITDB_ROOT_PASSWORD: pato11
      MONGO_INITDB_DATABASE: db
    ports:
      - 27017:27017